
localStorage.setItem('dummy', JSON.stringify([   {
    "id": 1,
    "name": "PERSONAL",
    "dataSize": "8",
    "description": "📞UNLIMITED STANDARD NATIONAL CALLS & TEXTS ✔️ESIM FREE TRIAL: 30 DAY FREE PLAN TRIAL WHEN ACTIVATING A NEW SERVICE ON AN ESIM WITH AN ESIM CAPABLE DEVICE. T&CS APPLY.✔️UP TO 200GB DATA ROLLOVER",
    "price": "15"
},
{
   "id": 2,
   "name": "PERSONAL",
   "dataSize": "40",
   "description": "📞UNLIMITED STANDARD NATIONAL CALLS & TEXTS ✔️ESIM FREE TRIAL: 30 DAY FREE PLAN TRIAL WHEN ACTIVATING A NEW SERVICE ON AN ESIM WITH AN ESIM CAPABLE DEVICE. T&CS APPLY.✔️UP TO 200GB DATA ROLLOVER",
   "price": "25"
},
{
"id": 3,
"name": "SMALL TEAM",
"dataSize": "60",
"description": "📞UNLIMITED STANDARD NATIONAL CALLS & TEXTS ✔️ESIM FREE TRIAL: 30 DAY FREE PLAN TRIAL WHEN ACTIVATING A NEW SERVICE ON AN ESIM WITH AN ESIM CAPABLE DEVICE. T&CS APPLY.✔️UP TO 200GB DATA ROLLOVER",
"price": "35"
},
{
"id": 4,
"name": "ENTERPRISE",
"dataSize": "70",
"description": "📞UNLIMITED STANDARD NATIONAL CALLS & TEXTS ✔️ESIM FREE TRIAL: 30 DAY FREE PLAN TRIAL WHEN ACTIVATING A NEW SERVICE ON AN ESIM WITH AN ESIM CAPABLE DEVICE. T&CS APPLY.✔️UP TO 200GB DATA ROLLOVER",
"price": "50"
}
]));



